### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by houhoulis**
Add Unlicense.

Alternative to PR #3 .

### CODE REVIEW

**Comment by yifu** [comment]
Hey @houhoulis I've just merged youre PR #4.
Two questions:
- Too late? 
- Should I have merge the PR#3 before?

Please confirm everyting looks fine on your side.

**Comment by houhoulis** [comment]
Great!!!!!!!!!!!!

Not too late 😄 

PR #3 and this PR add two different open-source licenses, each of which are accepted by GitHub, the OSI, and [the OpenVSX registry](https://open-vsx.org/). It's absolutely up to you what license you prefer.

TL;DR merging this PR is great. I'll close #3.

~I will try to submit the extension to the OpenVSX registry & let you know whether it succeeds.~ I can submit the extension to the OpenVSX registry, and I would be happy to do so! But I should point out first that the OpenVSX people [prefer authors to publish their own extensions as maintainers](https://github.com/open-vsx/publish-extensions#when-to-add-an-extension).

**Comment by houhoulis** [comment]
Here's the [quote](https://github.com/open-vsx/publish-extensions#when-to-add-an-extension) from the OpenVSX people:

> One goal of Open VSX is to have extension maintainers publish their extensions [according to the documentation](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). However, you may be missing specific extensions that have not been published by their maintainers: either they are not willing to do it, or they haven't found time to do it, or simply they haven't heard about Open VSX yet. Though the preferred solution for such a situation is to convince the maintainers to start publishing themselves, you can add the extensions here to have them published by our CI workflow.

Now that highlight-trailing-whitespaces has an open-source license, you can publish it officially to the OpenVSX registry, as they suggest. Or, if you'd rather not be bothered, I can submit it [via their CI](https://github.com/open-vsx/publish-extensions#how-to-add-an-extension).

Both ways will result in people being able to use highlight-trailing-whitespaces in VSCodium. You would show as the extension author exactly the same in both cases.

Would you like to publish to the OpenVSX registry as they suggest? Or should I submit via their CI?

**Comment by yifu** [comment]
> Would you like to publish to the OpenVSX registry as they suggest? Or should I submit via their CI?

Go ahead and submit it yourself. :-)

**Comment by houhoulis** [comment]
🎉 🎉 🎉

successfully added to VSCodium!

Thanks!

**Pull request merged**
